apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::258055694241:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-36FoG8mcQjd1
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::258055694241:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-20T16:47:31Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
    manager: vpcLambda
    operation: Update
    time: "2023-10-20T16:47:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1366"
  uid: 5a8833af-a457-4702-81b1-cf7a0d5a3efa
